name: buildandtest

on:
  push:
    branches:    
      - main
      - Primera_Entrega
 
jobs:
  linter: 
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v3
      - name: Super-linter
        uses: super-linter/super-linter@v5.7.2
        env: 
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_CSHARP: true
  build:
    runs-on: windows-latest


    steps:
      - uses: actions/checkout@v3


      - name: Setup .NET Core SDK 7
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

      - name: Install dependencies
        run: dotnet restore src/RestClient.Net.sln

      - name: Build
        run: dotnet build src/RestClient.Net.sln --no-restore

      - name: Test on .NET 7
        run: dotnet test src/RestClient.Net.UnitTests --no-build --verbosity normal --framework net7.0        
