name: .NET

on:
  push:
    branches: [ "actionbuild" ]
  pull_request:
    branches: [ "actionbuild" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 3.1.x
        
      - name: Restore dependencies
        run: dotnet restore
      
      - name: Build
        run: dotnet build --no-restore
      
      - name: Test .NET Standard
        run: dotnet test src/RestClient.Net.UnitTests --no-build --verbosity normal --framework netcoreapp3.1

      - name: Test .NET Standard
        run: dotnet test src/RestClient.Net.UnitTests --no-build --verbosity normal --framework net5.0
