name: Build Projects

on:
  push:
    branches: [ 5/develop ]
  pull_request:
    branches: [ 5/develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    - name: Install dependencies
      run: dotnet restore src/RestClient.Net.sln

    - name: Build
      run: dotnet build src/RestClient.Net.sln --configuration Release --no-restore 

